name: Cleanup Cloudinary
on:
  schedule:
    - cron: '0 16 * * 6' # 每週六 UTC 16:00 = 台灣週日 00:00
  workflow_dispatch: # 允許手動觸發

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run cleanup script
        env:
          CLOUDINARY_URL: ${{ secrets.CLOUDINARY_URL }}
        run: node cleanup.js
